-- NeoVim Entrypoint
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.telescope"
require "user.treesitter"
require "user.nvim-tree"
require "user.barbar"
require "user.toggleterm"
require "user.autopairs"
require "user.gitgutter"
require "user.lualine"
require "user.nightfox"
require "user.colorscheme"
